version: '3.8'

services:
  # Southwest USA Roadtripper App
  app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - .:/app
      - roadtripper_data:/app/data  # Persistent data volume
      - /app/node_modules  # Prevent node_modules override
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:/app/data/roadtripper.db"
      # Regional bounds for Southwest USA
      SOUTHWEST_BBOX: "-124.5,32.5,-109.0,42.0"
      # Will be set via .env file
      MAPBOX_PUBLIC_TOKEN: "${MAPBOX_PUBLIC_TOKEN}"
      OPENROUTE_API_KEY: "${OPENROUTE_API_KEY}"
    ports:
      - "5173:5173"  # Vite dev server port
    deploy:
      resources:
        limits:
          # Resource limits for MacBook Air M2 16GB
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    restart: unless-stopped
    
volumes:
  roadtripper_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data  # Map to local data directory
